name: ci

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  build:
    if: contains(toJson(github.event.commits), '[ci skip]') == false
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2019, ubuntu-latest, macos-12]

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: bash ./scripts/build.sh
      
    - name: Validate
      run: |
        bash ./scripts/validate-clap.sh
        bash ./scripts/validate-vst.sh
